### ISSUE TITLE
Display the completed time in the complete property.

### ISSUE THREAD

**Issue by yoghurtdewdew** [DimitryDushkin/logseq-plugin-task-check-date#13]
Display the completed time in the complete property. I wish after the [[date]], there will be a HH:mm, to tell me more information about when I did that and the time order of the matters to recall the details.

**Comment by DimitryDushkin** [comment]
Hey! Sounds like a great option to add. I’m not actively developing it right now but happy to review PR.

**Comment by gf3** [comment]
Hi @yoghurtdewdew see #17 which supports adding & configuring the completion time

**Comment by DimitryDushkin** [comment]
New release with the feature dropped!
