### ISSUE TITLE
takes too long to load

### ISSUE THREAD

**Issue by hodanli** [DimitryDushkin/logseq-plugin-task-check-date#8]
![image](https://user-images.githubusercontent.com/6535865/212957058-67d70a2e-a520-4955-a3e0-eb499e307adb.png)

i get this warning when opening logseq.

**Comment by DimitryDushkin** [comment]
Thanks for report! Turned out I forget to add new JS bundle to repo :( Fixed in 1.0.5 which is rolling out now

**Comment by DimitryDushkin** [comment]
Please reopen if issue persists
