### ISSUE TITLE
querying completed issues by date does not work without re-indexing on logseq 0.8.18

### ISSUE THREAD

**Issue by svnk** [DimitryDushkin/logseq-plugin-task-check-date#9]
I tried 
{{query (property completed [[2023-03-01 Wednesday]]  )  }} (my journal page format for today) and that did not turn up any results although I DID complete tasks. (and I know - to query "today" I need to turn to advanced queries...

aftter playing around with other properties I found the following difference in dev tools (show block data)

brb:: [[2023-03-01 Wednesday]]
turns into 
:block/properties {:brb #{"2023-03-01 Wednesday"}} 

whereas the "completed" block property by the plugin looks like this
completed:: [[2023-03-01 Wednesday]]
turns into
:block/properties {:completed "[[2023-03-01 Wednesday]]"},

then I tried manuall adding that '#' and turning 
completed:: [[2023-03-01 Wednesday]] 
into
completed:: #[[2023-03-01 Wednesday]]

made {{query (property completed [[2023-03-01 Wednesday]]  )  }} return that block as result.

**Comment by svnk** [comment]
playing around a bit more: ANY edit on the "completed" property makes it turn into
completed:: #[[2023-03-01 Wednesday]]
and searchable. (even adding a space and removing it again.

**Comment by meain** [comment]
Probably related: Completed items does not show up in the linked references for the journal page until I restart LogSeq.

**Comment by svnk** [comment]
For me (logseq 0.8.18) re-starting logseq does not change anything. Still only manually edited completion properties show up.

But re-indexing DOES make them show up in "linked references" of journal pages and in queries like "{{query (property completed [[2023-03-01 Wednesday]]  )  }}"

Wonder if that is a bug in the plugin or a bug in logseq itself...

**Comment by yuluoxingzhao** [comment]
我遇到了同样的问题,不知道是插件冲突或其他造成了,目前没有办法解决.请问您是怎么解决查询的

**Comment by yuluoxingzhao** [comment]
{{query (and [[20230315]] "completed")}} 解决了

**Comment by kerim** [comment]
Is this still an issue? I just tested it and it seems to be working now without a reindex?

**Comment by ak127a** [comment]
This issue still persists in the latest version v0.9.19

As mentioned above, adding # manually fixes it

**Comment by Faldrian** [comment]
Can the plugin trigger a re-index on the item / block / page that contains the completed task, so the index is automatically updated?
